### ISSUE TITLE
x86 letsgo error

### ISSUE THREAD

**Issue by cctv130** [wallds/NoVmpy#18]
[hook_mem_unmapped]:  21 0xffa6971d 1 0
[hook_code] address: 0xFFA6971D size: 0xF1F1F1F1 what?
Traceback (most recent call last):
  File "D:\tool/ida/plugins\novmpy\ui.py", line 17, in activate
    vtil_graph.show_graph(ea)
  File "D:\tool/ida/plugins\novmpy\views\vtil_graph.py", line 462, in show_graph
    lifter.lift_il(None, VMState(current_handler=ea))
  File "D:\tool/ida/plugins\novmpy\vm_lifter.py", line 92, in lift_il
    assert parse_result
AssertionError

**Comment by Eagle1020** [comment]
I have the same problem when I use it

**Comment by seto-kaiba-0** [comment]
Same
[hook_mem_unmapped]:  21 0xb1e2b39a 1 0
[hook_code] address: 0xB1E2B39A size: 0xF1F1F1F1 what?
Traceback (most recent call last):
  File "C:\IDA9/plugins\novmpy\ui.py", line 17, in activate
    vtil_graph.show_graph(ea)
  File "C:\IDA9/plugins\novmpy\views\vtil_graph.py", line 462, in show_graph
    lifter.lift_il(None, VMState(current_handler=ea))
  File "C:\IDA9/plugins\novmpy\vm_lifter.py", line 92, in lift_il
    assert parse_result
AssertionError
